### ISSUE TITLE
Error when dragging file to Oodle Compress

### ISSUE THREAD

**Issue by gekon420** [Tamely/Oodle-Compressor#1]
![Bez nazwy](https://github.com/user-attachments/assets/ee5c5a5e-4579-434e-8c3d-39fa98c234e8)

**Comment by Tamely** [comment]
![image](https://github.com/user-attachments/assets/15b6ec64-4845-47e3-bcf4-47ffa775299b)

**Comment by gekon420** [comment]
but where to get oodle.dll?

**Comment by Tamely** [comment]
Get a license. I can't help as that has nothing to do with this repo.

**Comment by gekon420** [comment]
Are they giving it to anyone who just writes to their email?

**Comment by Tamely** [comment]
No... it's a license, they're not a charity.

**Comment by gekon420** [comment]
so can i buy it?
